trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  webAppName: 'fati' 

stages:
- stage: Build
  displayName: 'Build ve Test'
  jobs:
  - job: BuildAndTest
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK'
      inputs:
        packageType: 'sdk'
        version: '8.0.x'
        
    - script: dotnet restore
      displayName: 'Restore Packages'
      
    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'Build Application'
      
    - script: dotnet test --configuration $(buildConfiguration) --no-build
      displayName: 'Run Tests'
      continueOnError: true
      
    - task: DotNetCoreCLI@2
      displayName: 'Publish Application'
      inputs:
        command: 'publish'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/publish'

        
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifacts'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  displayName: 'Deploy to Azure'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: Deploy
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'
        
    - task: AzureWebApp@1
      displayName: 'Deploy Azure Web App'
      inputs:
        azureSubscription: 'fati'
        appType: 'webAppLinux'  
        appName: '$(webAppName)'
        package: '$(System.ArtifactsDirectory)/drop/publish'
        deploymentMethod: 'auto'
        runtimeStack: 'DOTNETCORE|8.0'  # 
